default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: code_mentor_development

test:
  <<: *default
  database: code_mentor_test

production:
  primary: &primary_production
    <<: *default
    database: code_mentor_production
    username: code_mentor
    password: <%= ENV["CODE_MENTOR_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: code_mentor_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: code_mentor_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: code_mentor_production_cable
    migrations_paths: db/cable_migrate
